# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_cla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syu_cla_set', to='page.ClassRoom'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_parent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_par_set', to='page.Parent'),
        ),
    ]
