# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20170522_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='par_tel',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tea_tel',
            field=models.CharField(max_length=11),
        ),
    ]
