# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='user_state',
            field=models.CharField(default='教师', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='user_tel',
            field=models.CharField(default='110', max_length=11),
        ),
        migrations.AddField(
            model_name='user',
            name='user_true_name',
            field=models.CharField(default='赵强', max_length=50),
        ),
    ]
