# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20170601_1719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
