# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_deliverrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverrecord',
            name='deliver_choice',
            field=models.CharField(default='默认：无', max_length=11),
        ),
    ]
