# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_deliverrecord_deliver_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='tea_age',
            field=models.IntegerField(default=25),
        ),
    ]
